<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions 
    targetNamespace="http://soap.crmapi.util.redknee.com/common/xsd/Common-v1.1" 
    xmlns:tns="http://soap.crmapi.util.redknee.com/common/xsd/Common-v1.1" 
    xmlns:dtns="http://soap.crmapi.util.redknee.com/common/xsd/2008/08" 
    xmlns:exns="http://soap.crmapi.util.redknee.com/common/exception/xsd/2008/08" 
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
    xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <wsdl:documentation>Common API for CRMAPI Version 2.1 on April 17th, 2009</wsdl:documentation>

    <wsdl:types>
        <xs:schema attributeFormDefault="qualified" elementFormDefault="qualified"
            targetNamespace="http://soap.crmapi.util.redknee.com/common/xsd/Common-v1.1">
            
            <xs:import namespace="http://soap.crmapi.util.redknee.com/common/xsd/2008/08" schemaLocation="Common_types_1_1.xsd" />
            
            <xs:element name="SuccessfulResponse" type="tns:SuccessfulResponse" />
            <xs:complexType name="SuccessfulResponse">
                <xs:sequence>
                    <xs:element name="result" type="dtns:SuccessCode" />
                </xs:sequence>
            </xs:complexType>
        </xs:schema>
    </wsdl:types>

    <wsdl:message name="successfulResponse">
        <wsdl:part element="tns:SuccessfulResponse" name="part1" />
    </wsdl:message>

</wsdl:definitions>
