<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions
    name="Crmapi_faults" 
    targetNamespace="http://soap.crmapi.util.redknee.com/common/exception/xsd/2008/08" 
    xmlns="http://schemas.xmlsoap.org/wsdl/" 
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
    xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    xmlns:tns="http://soap.crmapi.util.redknee.com/common/exception/xsd/2008/08">

    <wsdl:documentation>CRMAPI Version 2.0 on August 6th, 2008</wsdl:documentation>

    <wsdl:types>
        <xs:schema attributeFormDefault="qualified" elementFormDefault="qualified">
            <xs:import namespace="http://soap.crmapi.util.redknee.com/common/exception/xsd/2008/08" schemaLocation="Common_fault_types_1_0.xsd" />
        </xs:schema>
    </wsdl:types>

    <wsdl:message name="CRMExceptionFault">
        <wsdl:part name="CRMException" element="tns:CRMException" />
    </wsdl:message>

</wsdl:definitions>